CajaPopular/Controllers/Vistas/avalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CajaPopular;

namespace CajaPopular.Controllers.Vistas
{
    public class avalsController : Controller
    {
        private caja_popular2Entities db = new caja_popular2Entities();

        // GET: avals
        public async Task<ActionResult> Index()
        {
            var avals = db.avals.Include(a => a.persona);
            return View(await avals.ToListAsync());
        }

        // GET: avals/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            aval aval = await db.avals.FindAsync(id);
            if (aval == null)
            {
                return HttpNotFound();
            }
            return View(aval);
        }

        // GET: avals/Create
        public ActionResult Create()
        {
            ViewBag.id_persona = new SelectList(db.personas, "uid", "nombre");
            return View();
        }

        // POST: avals/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "uid,id_persona,num_socio")] aval aval)
        {
            if (ModelState.IsValid)
            {
                db.avals.Add(aval);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.id_persona = new SelectList(db.personas, "uid", "nombre", aval.id_persona);
            return View(aval);
        }

        // GET: avals/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            aval aval = await db.avals.FindAsync(id);
            if (aval == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_persona = new SelectList(db.personas, "uid", "nombre", aval.id_persona);
            return View(aval);
        }

        // POST: avals/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "uid,id_persona,num_socio")] aval aval)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aval).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.id_persona = new SelectList(db.personas, "uid", "nombre", aval.id_persona);
            return View(aval);
        }

        // GET: avals/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            aval aval = await db.avals.FindAsync(id);
            if (aval == null)
            {
                return HttpNotFound();
            }
            return View(aval);
        }

        // POST: avals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            aval aval = await db.avals.FindAsync(id);
            db.avals.Remove(aval);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CajaPopular/Controllers/Vistas/rel_solicitante_avalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CajaPopular;

namespace CajaPopular.Controllers.Vistas
{
    public class rel_solicitante_avalController : Controller
    {
        private caja_popular2Entities db = new caja_popular2Entities();

        // GET: rel_solicitante_aval
        public async Task<ActionResult> Index()
        {
            var rel_solicitante_aval = db.rel_solicitante_aval.Include(r => r.aval).Include(r => r.solicitante);
            return View(await rel_solicitante_aval.ToListAsync());
        }

        // GET: rel_solicitante_aval/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            rel_solicitante_aval rel_solicitante_aval = await db.rel_solicitante_aval.FindAsync(id);
            if (rel_solicitante_aval == null)
            {
                return HttpNotFound();
            }
            return View(rel_solicitante_aval);
        }

        // GET: rel_solicitante_aval/Create
        public ActionResult Create()
        {
            ViewBag.id_aval = new SelectList(db.avals, "uid", "num_socio");
            ViewBag.id_solicitante = new SelectList(db.solicitantes, "uid", "num_solicitante");
            return View();
        }

        // POST: rel_solicitante_aval/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id_solicitante,id_aval,cantidad,ingresos_mensuales,ingresos_extra,gastos_mensuales,otras_deudas")] rel_solicitante_aval rel_solicitante_aval)
        {
            if (ModelState.IsValid)
            {
                db.rel_solicitante_aval.Add(rel_solicitante_aval);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.id_aval = new SelectList(db.avals, "uid", "num_socio", rel_solicitante_aval.id_aval);
            ViewBag.id_solicitante = new SelectList(db.solicitantes, "uid", "num_solicitante", rel_solicitante_aval.id_solicitante);
            return View(rel_solicitante_aval);
        }

        // GET: rel_solicitante_aval/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            rel_solicitante_aval rel_solicitante_aval = await db.rel_solicitante_aval.FindAsync(id);
            if (rel_solicitante_aval == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_aval = new SelectList(db.avals, "uid", "num_socio", rel_solicitante_aval.id_aval);
            ViewBag.id_solicitante = new SelectList(db.solicitantes, "uid", "num_solicitante", rel_solicitante_aval.id_solicitante);
            return View(rel_solicitante_aval);
        }

        // POST: rel_solicitante_aval/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id_solicitante,id_aval,cantidad,ingresos_mensuales,ingresos_extra,gastos_mensuales,otras_deudas")] rel_solicitante_aval rel_solicitante_aval)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rel_solicitante_aval).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.id_aval = new SelectList(db.avals, "uid", "num_socio", rel_solicitante_aval.id_aval);
            ViewBag.id_solicitante = new SelectList(db.solicitantes, "uid", "num_solicitante", rel_solicitante_aval.id_solicitante);
            return View(rel_solicitante_aval);
        }

        // GET: rel_solicitante_aval/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            rel_solicitante_aval rel_solicitante_aval = await db.rel_solicitante_aval.FindAsync(id);
            if (rel_solicitante_aval == null)
            {
                return HttpNotFound();
            }
            return View(rel_solicitante_aval);
        }

        // POST: rel_solicitante_aval/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            rel_solicitante_aval rel_solicitante_aval = await db.rel_solicitante_aval.FindAsync(id);
            db.rel_solicitante_aval.Remove(rel_solicitante_aval);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CajaPopular/Views/avals/Create.cshtml
@model CajaPopular.aval

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<<<<<<< HEAD
<h2>Create</h2>
=======
<h2>Crear Nuevo</h2>
>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
<<<<<<< HEAD
        <h4>aval</h4>
=======
        <h4>Aval</h4>
>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id_persona, "id_persona", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_persona", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_persona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.num_socio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.num_socio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.num_socio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
<<<<<<< HEAD
                <input type="submit" value="Create" class="btn btn-default" />
=======
                <input type="submit" value="Crear" class="btn btn-primary" />
>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
            </div>
        </div>
    </div>
}

<div>
<<<<<<< HEAD
    @Html.ActionLink("Back to List", "Index")|
    @Html.ActionLink("Crear Relación entre Solicitante y Aval", "Create", "rel_solicitante_aval")
=======
    @Html.ActionLink("Regresar", "Index")
>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CajaPopular/Views/avals/Delete.cshtml
@model CajaPopular.aval

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<<<<<<< HEAD
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>aval</h4>
=======
<h2>Borrar</h2>
<h4>Aval</h4>

<h3>¿Seguro que quieres borrar esto?</h3>
<div>
    
>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.num_socio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.num_socio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.persona.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.persona.nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
<<<<<<< HEAD
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
=======
            <input type="submit" value="Borrar" class="btn btn-primary" /> 
            </div>
            <br />
            <div>

            @Html.ActionLink("Regresar", "Index")
>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
        </div>
    }
</div>

CajaPopular/Views/avals/Details.cshtml
@model CajaPopular.aval

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<<<<<<< HEAD
<h2>Details</h2>

<div>
    <h4>aval</h4>
=======
<h2>Detalles</h2>

<div>
    <h4>Aval</h4>
>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.num_socio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.num_socio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.persona.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.persona.nombre)
        </dd>

    </dl>
</div>
<p>
<<<<<<< HEAD
    @Html.ActionLink("Edit", "Edit", new { id = Model.uid }) |
    @Html.ActionLink("Back to List", "Index")
</p>
=======
    @Html.ActionLink("Editar", "Edit", new { id = Model.uid }) |
    @Html.ActionLink("Regresar", "Index")    
</p>
>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b

CajaPopular/Views/avals/Edit.cshtml
@model CajaPopular.aval

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<<<<<<< HEAD
<h2>Edit</h2>
=======
<h2>Editar</h2>
>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
<<<<<<< HEAD
        <h4>aval</h4>
=======
        <h4>Aval</h4>
>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.uid)

        <div class="form-group">
            @Html.LabelFor(model => model.id_persona, "id_persona", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_persona", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_persona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.num_socio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.num_socio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.num_socio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
<<<<<<< HEAD
                <input type="submit" value="Save" class="btn btn-default" />
=======
                <input type="submit" value="Guardar" class="btn btn-primary" />
>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
            </div>
        </div>
    </div>
}

<div>
<<<<<<< HEAD
    @Html.ActionLink("Back to List", "Index")
=======
    @Html.ActionLink("Regresar", "Index")
>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CajaPopular/Views/avals/Index.cshtml
@model IEnumerable<CajaPopular.aval>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<<<<<<< HEAD
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
=======
<h2>Avales</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Create")
>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.num_socio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.persona.nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.num_socio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.persona.nombre)
        </td>
        <td>
<<<<<<< HEAD
            @Html.ActionLink("Edit", "Edit", new { id=item.uid }) |
            @Html.ActionLink("Details", "Details", new { id=item.uid }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.uid })
=======
            @Html.ActionLink("Editar", "Edit", new { id=item.uid }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.uid }) |
            @Html.ActionLink("Borrar", "Delete", new { id=item.uid })
>>>>>>> 6e1296d4a735628ed03e8ab9d57936a716dd9e7b
        </td>
    </tr>
}

</table>